osx_image: xcode7.3
language: objective-c
script: 
before_deploy: 
  - set -x
  - . ./utils.sh && if is_ole_magnus; then export OLE-MAGNUS=YES; else export OLE-MAGNUS=NO; fi 
deploy:
  provider: pages
  github_token: $GITHUB_API_KEY 
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    condition: $OLE-MAGNUS = YES
    repo: olemaga/TestSDK
