osx_image: xcode7.3
language: objective-c
script: 
before_deploy: echo 'deployed file with tag $TRAVIS_TAG' > deploy.md
deploy:
  provider: pages
  api_key: $GITHUB_API_KEY 
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master
    repo: olemaga/TestSDK
