osx_image: xcode7.3
language: objective-c
script: 
deploy:
  provider: pages
  github_token: $GITHUB_API_KEY 
  skip_cleanup: true
  overwrite: true
  on:
    condition: $(sh utils.sh) == "YES"
    branch: master
    repo: olemaga/TestSDK
